### ISSUE TITLE
Consider whether new updates to the installer would require any changes for us

### ISSUE THREAD

**Issue by mattstauffer** [tighten/lambo#147]
https://laravel-news.com/laravel-installer-git

I assume no since I don't think we're wrapping the installer anymore, but my kids are screaming right now so I don't have a fully functional brain so I'm just gonna leave this for when I or someone else has a full brain

**Comment by jonsugar** [comment]
Currently, we are wrapping the installer but we did agree to remove it since all it does is wrap composer.

Once the Laravel Installer is removed we will not be required to make changes, the question is more like "does it make sense for us to match/replicate this new/changed/removed feature. Does the community expect parity in this instance?"

**Comment by mattstauffer** [comment]
OK, sounds good -- thanks! I'm totes OK with us adding it. Will add an issue for it.
